#!/bin/bash

INGRESO=$2
USUARIO=$1

aplay `ls ../voice/working/* | shuf -n 1`

notify-send 'Markopolo' 'Buscando en Youtube'

TARGET=`echo $INGRESO | sed 's/\(^.*videos+de+\|^.*youtube+\)//g'`

firefox --new-tab "https://www.youtube.com/results?search_query=$TARGET" &

aplay `ls ../voice/endwork/* | shuf -n 1`

echo 'Buscando en Youtube...'
