#!/bin/bash

USER=$1
ANSWER=$2



QUESTION="Ah si... he escuchado hablar de $ANSWER. Tiene arboles?"

WAIT_TIME='20s'

FINGER_FILE=saybye03

TIME_OUT_ACTION='

notify-send "Trinity" "Me hubiera gustado saber sobre la vegetacion del lugar."

'

###################################################################################
############  NO EDIT #############################################################
###################################################################################
trinity-makequestion "$QUESTION" "$WAIT_TIME" "$FINGER_FILE" "$TIME_OUT_ACTION"
