#!/bin/bash

INGRESO=$2
USUARIO=$1

trinity-randomwav working

notify-send 'Trinity' 'Buscando en Pinterest'

TARGET=`echo $INGRESO | sed 's/\(^.*imagenes+de+\|^.*pinterest+\)//g'`

firefox --new-tab "https://ar.pinterest.com/search/pins/?q=$TARGET" &

echo 'Buscando en Pinterest'
