#!/bin/bash

INGRESO="`echo $2 | sed 's/+/ /g' | sed 's/^@//g'`"
USUARIO=$1

echo $USUARIO, no entiendo que quieres decir con \"$INGRESO\". Creo que querias hacer algo con una foto. Pero no entendi bien.
