#!/bin/bash

INGRESO=$2
USUARIO=$1

trinity-randomwav working &

TARGET=`echo $INGRESO | sed s/^.*internet//g`

firefox --new-tab "https://www.google.com/search?q=$TARGET" &> /dev/null &

echo 'Google fue abierto'
